### ISSUE TITLE
Contributors Section

### ISSUE THREAD

**Issue by jwoo92** [FCCColumbus/fcc-columbus#10]
On the homepage, it would be nice to have a contributors section that includes an array of all contributors with a reusable component for contributors.

To add to this thought, it might be best if we eliminate the 'admins' section so there is no feel for any type of 'ranking system'. Then we will have one accumulative group section that is seen as together as a team and organization, and not dictated by any one person or select group.

**Comment by saelili** [comment]
I think it's a good idea to keep some sort of admin section or otherwise indicate admins within a contributor list. It doesn't have to be flashy or call a lot of attention to admins but I think making them easy to find is important in case anyone needs to find someone to contact directly. Our email address is useful for that of course, but I can think of scenarios where someone might want to speak to an admin personally or through a direct message.
